### ISSUE TITLE
spritz_state_memzero(spritz_ctx *ctx)

### ISSUE THREAD

**Issue by RobTillaart** [abderraouf-adjal/ArduinoSpritzCipher#10]
can be faster with **memset()** 
See #7 

```cpp
  do {
    ctx->s[i] = 0;
  } while (++i);
```

==>

```cpp
memset(ctx->s[i], 0, 255);

**Comment by abderraouf-adjal** [comment]
Some compilers and environments choose to completely remove the `memset()` calls on high optimization, so I made the function compiled with `-O0`.

Yes the `memset()` can be faster by like 4 or 5 instruction maybe? I did not count the possible stack pop and push overhead.
Assembly: <https://godbolt.org/z/6h8xWW>
AVR `memset()`: [avr-libc/libc/string/memset.S](https://github.com/vancegroup-mirrors/avr-libc/blob/master/avr-libc/libc/string/memset.S).

Note that some highly portable `libc` libraries use pure ISO C code so it's the same result (Almost with calling external function overhead).

What can be done? Adding a macro for user to choose if he wanna use `libc` calls sound like an okay solution.

**Comment by RobTillaart** [comment]
If a lot of data has to be de/encrypted any time gained is important in terms of time = money = energy etc.
So a compiler option sounds like a solution 

you might add a disclaimer in the documentation 'optimize at own risk'

**Comment by abderraouf-adjal** [comment]
Done:
<https://github.com/abderraouf-adjal/ArduinoSpritzCipher/commit/f80162dad5f84e868f101f3a134df92b53b4f66b>
<https://github.com/abderraouf-adjal/ArduinoSpritzCipher/commit/f09748d86ceb591cadc370a56b88be557cb0eeb9>
<https://github.com/abderraouf-adjal/ArduinoSpritzCipher/commit/686c952c779e0331d91cde9debfea9e91bfddb2f>
