### ISSUE TITLE
spritz_random32_uniform

### ISSUE THREAD

**Issue by RobTillaart** [abderraouf-adjal/ArduinoSpritzCipher#11]
this random function will work in practice, however depending on the UPPER bound (esp large values) it is not uniform

imagine your random generator generates 0 .. 9
and you set the upper bound to  7 
then the numbers 0,1,2 have twice as many chance of being chosen than numbers 3,4,5,6,7,8 and 9.
this is because UPPER and MAX random are same order of magnitude.

When UPPER bound is small  it is still not uniform but the bias will be substantial smaller (less problematic)

**Comment by abderraouf-adjal** [comment]
This algorithm is used almost in all crypto libs and in operating systems such as FreeBSD OS RNG.

This is made to avoiding modulo bias which you are mentioning are you sure it's wrong/broken algorithm?

**Comment by RobTillaart** [comment]
I do not see how this algorithm avoids the modulo bias. Do you have a link to a good explanation?

**Comment by abderraouf-adjal** [comment]
This algorithm is used started in OpenBSD OS, and now it's used in many places such as Linux, OpenSSL, OpenSSH, Android, tc...
the original code is in: <https://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/src/lib/libc/crypt/arc4random.c?rev=1.55&content-type=text/plain&only_with_tag=HEAD>

Here is an explanation for it in an RNG library: <https://www.pcg-random.org/posts/bounded-rands.html#debiased-modulo-twice-openbsds-method>

You can contact the dev. from OpenBSD for more documentation about it.

**Comment by RobTillaart** [comment]
OK thanks for the link (and all patches)
I will close this issue and only reopen it if needed.

**Comment by RobTillaart** [comment]
The link is a good explanation. Thanks,

1) worst case happens when upper_bound is 2^31 + 1 ==> min = 2^31 -1   so the range of valid values is minimal.(~50%)
2) drawback is algorithm needs two % operations which are relative expensive if there is no co processor

----
point (2) can partially be optimized in case the upper_bound stays constant over multiple subsequent calls. 
(speed vs memory exchange). Is that a typical use?

```cpp
uint32_t
spritz_random32_uniform(spritz_ctx *ctx, uint32_t upper_bound)
{
  static uint32_t min = 0, ub = 0;    // to hold last used values
  uint32_t r;

  if (upper_bound < 2)
  {
    return 0;
  }
  
  if (ub != upper_bound)      //  only recalculate if needed.
  {
    ub = upper_bound;
    /* 2**32 % x == (2**32 - x) % x */
    min = (uint32_t)(-ub % ub);
  }

  /* This could theoretically loop forever but each retry has
   * p > 0.5 (worst case, usually far better) of selecting a
   * number inside the range we need, so it should rarely need
   * to re-roll.
   */
  for (;;) {
    r = spritz_random32(ctx);
    if (r >= min)
    {
      return (uint32_t)(r % ub);
    }
  }
}
```
----
The modulo in line ```return (uint32_t)(r % ub);``` is not needed if and only if the range [min, 2^32] === [0, upper_bound]
That is for ~50% of the possible values for upper_bound. 
Note: This is independent of the above caching strategy of upper_bound.

```cpp
uint32_t
spritz_random32_uniform(spritz_ctx *ctx, uint32_t upper_bound)
{
  static uint32_t min = 0, ub = 0;    // to hold last used values
  uint32_t r;

  if (upper_bound < 2)
  {
    return 0;
  }
  
  if (ub != upper_bound)      //  only recalculate if needed.
  {
    ub = upper_bound;
    /* 2**32 % x == (2**32 - x) % x */
    min = (uint32_t)(-ub % ub);
  }

  /* This could theoretically loop forever but each retry has
   * p > 0.5 (worst case, usually far better) of selecting a
   * number inside the range we need, so it should rarely need
   * to re-roll.
   */
  for (;;) {
    r = spritz_random32(ctx);
    if (r >= min)
    {
      if ( ub <= (1 << 31)) return (uint32_t)(r % ub);
      else return r - min;      // no 'expensive' modulo needed.
    }
  }
}
```
if upper_bound is always below 2^31 this 'optimization' will never be used and in fact add a 32 bit compare in every call.

----

If upper_bound is known to be 0..31 there is another fast trick - bit_count
```cpp
uint8_t_t
spritz_random32_uniform_32(spritz_ctx *ctx, uin8_t upper_bound)
{
  uint8_t count = 0U;
  uint32_t r;

  if (upper_bound < 2) return 0;

  r = spritz_random32(ctx);
  for (uint8_t i = 0; i < upper_bound; i++)
  {
    if (r & 1U ) count ++;
    r >>= 1;
  }
  return count;
}
```
in fact, one could cache the value of r (static) as it may hold enough bits for next call. 
(used this in the past to simulate 5 throws of a dice with one 32 bit call to random()  )

----
The very similar trick can also be used for larger values too.. One 32 bit random number equals two 16 bit patterns, three 10 bit patterns, four 8 bit patterns or five 6 bit patterns up to  32 one bit patterns.

 So if upperbound < 16 bits only one call to random is needed...

```cpp
uint16_t_t
spritz_random32_uniform_16(spritz_ctx *ctx, uin16_t upper_bound)
{
  static uint32_t bits;
  static uint8_t bitsleft = 0;

  if (upper_bound < 2) return 0;
  uint8_t cnt = bits needed for upperbound (some loop with shifts +1)

  for (;;)
  {
    if (bitsleft < cnt)
    {
      bits = spritz_random32(ctx);
      bitsleft = 32;
    }
    r = bits >> cnt;    
    bitsleft -= cnt;
    if (r < upper_bound) return r;
  }
}
```

just to share some thoughts that popped up

**Comment by abderraouf-adjal** [comment]
Yes it's possible to do that (static variable) but `spritz_random32_uniform()` will not be thread-safe anymore for an RTOS, correct me if I'm wrong.

> if upper_bound is always below 2^31 this 'optimization' will never be used and in fact add a 32 bit compare in every call.

Usually this function used to make visible passwords/keys, so yes, there is no sweet way to optimize this and stay "a universal" code that can run in any machine and OS.
Any further optimization from the current code point to more specific usage case that will bring a negative side.

The only nice optimization that can not give out much side effects is a parallel `u32_uniform()` that fill out an array of length `N`:  
`void u32_uniform(spritz_ctx *ctx, uin16_t upper_bound, uint32_t *array, size_t array_len)`

And about the modulo op, if the machine is very basic like ATmega328P it will not take noticeable time to make something like 16-length password/key which is the usual usage for this:
<https://android.googlesource.com/toolchain/gcc/+/3f73d6ef90458b45bbbb33ef4c2b174d4662a22d/gcc-4.6/gcc/config/avr/libgcc.S#472>

The time-consuming op is `__udivmodsi4` which the function will use two times (min & output).

Your research is interesting, thank you.

**Comment by abderraouf-adjal** [comment]
Earlier I did give you the wrong link from OpenBSD (new version code moved),
So here is the right link: <https://cvsweb.openbsd.org/cgi-bin/cvsweb/src/lib/libc/crypt/arc4random.c?rev=1.40&content-type=text/x-cvsweb-markup>

Since you are interested, check this old version of it that has some optimization code:
<https://opensource.apple.com/source/OpenSSH/OpenSSH-166/openssh/openbsd-compat/bsd-arc4random.c>

```c
uint32_t
arc4random_uniform(uint32_t upper_bound)
```
