### ISSUE TITLE
new function - spritz_crypt_inplace

### ISSUE THREAD

**Issue by RobTillaart** [abderraouf-adjal/ArduinoSpritzCipher#12]
```cpp
spritz_crypt_inplace(spritz_ctx *ctx, uint8_t *data, uint16_t dataLen)
{
  uint16_t i = dataLen;
  while( i > 0)    // cmp with zero is fast
  {
    data[--i] ^= drip(ctx);
  }
}
```

**Comment by abderraouf-adjal** [comment]
A user can just do `spritz_crypt(&s_ctx, msg, msgLen, msg);`.

> cmp with zero is fast
This depend on the architecture and optimization, in the assembler level with `-Os` (Arduino default) it's the same compare code:

**AVR:**
```
cp r28,r16
cpc r29,r17
breq .L29
```

If we use `inplace()` we get ~4 instructions (AVR) less in code and ~4 less in stack management

**ARM:** almost  the same too.

```
spritz_crypt:
        push    {r4, r5, r6, r7, r8, lr}
        mov     r8, r0
        mov     r4, r1
        sub     r6, r3, #1
        add     r7, r1, r2
.L26:
        cmp     r4, r7
        popeq   {r4, r5, r6, r7, r8, pc}
        mov     r0, r8
        ldrb    r5, [r4], #1    @ zero_extendqisi2
        bl      drip
        eor     r0, r0, r5
        strb    r0, [r6, #1]!
        b       .L26


spritz_crypt_inplace:
        push    {r4, r5, r6, lr}
        mov     r6, r0
        mov     r5, r1
        mov     r4, r2
.L31:
        cmp     r4, #0
        popeq   {r4, r5, r6, pc}
        mov     r0, r6
        bl      drip
        sub     r4, r4, #1
        lsl     r2, r4, #16
        ldrb    r3, [r5, r2, lsr #16]   @ zero_extendqisi2
        lsr     r4, r2, #16
        eor     r0, r0, r3
        strb    r0, [r5, r2, lsr #16]
        b       .L31
```

What's your opinion, does it worth adding `inplace()`?

**Comment by RobTillaart** [comment]
Most important reasons for me are:  (random order)
1) the application does not need two buffers = RAM = important on minimal systems
2) the original message will be no longer in RAM than strictly necessary.
3) could be convenient for user to have the choice. 

Performance was not the argument, 

(I should have added this argumentation in the first post above, sorry for that)

**Comment by abderraouf-adjal** [comment]
Done:
<https://github.com/abderraouf-adjal/ArduinoSpritzCipher/commit/7bf777e40dfefb192eb42c260394e6ad6b410541>
<https://github.com/abderraouf-adjal/ArduinoSpritzCipher/commit/dd9c3db635f638eab1117733a91c61ea70f77870>

**Comment by RobTillaart** [comment]
Might need an example sketch? 
show how to use, maybe to show it does use less RAM.

**Comment by abderraouf-adjal** [comment]
Done: <https://github.com/abderraouf-adjal/ArduinoSpritzCipher/blob/master/examples/SpritzCryptInplaceTest/SpritzCryptInplaceTest.ino>
