### ISSUE TITLE
How to make this compatible with ARC4 / RC4?

### ISSUE THREAD

**Issue by leelx78** [abderraouf-adjal/ArduinoSpritzCipher#13]
Hi I have an Arduino application that requires compatibility with ARC4. 

I have the SpritzCipher library already installed and I like it a lot so is there a way that I can initialise the cipher so that it remove all additional features of the Spritz algorithm and becomes compatible with ARC4/RC4? 

I realise this reduces security but it would be good to have this flexibility when required.

Please let me know thanks!

**Comment by abderraouf-adjal** [comment]
Well, ARC4 is a stream cipher only (no MAC, no HASH, no IV or nonce), the closest setup to ARC4 is using:
```
void spritz_setup(spritz_ctx *ctx, const uint8_t *key, uint8_t keyLen) // Init
void spritz_crypt(spritz_ctx *ctx, const uint8_t *data, uint16_t dataLen, uint8_t *dataOut) 
```

However I'm not sure what do you mean by **compatible with ARC4/RC4**. If you mean by API/usage then your answer is above, if you mean getting same result/data bit by bit then you should know that Spritz is a different algorithm.

**Comment by leelx78** [comment]
Hi @abderraouf-adjal  thanks so much for the quick reply.

By "compatible" I mean the answer should be the same as a ARC4 algorithm so they can exchange data so I guess that's out of the question.

Do you have any suggestions on a good way to implement ARC4/RC4 on Arduino? I use ESP32-S2

I see https://tls.mbed.org/api/arc4_8h.html is an option but I can't get that to work on ESP32-S2

Thanks!

**Comment by abderraouf-adjal** [comment]
You cannot, they are not the same structure, so if you need the answer to be the same use ARC4. 
And for an ARC4 implementation you can use this one: [rc4.c](https://opensource.apple.com/source/xnu/xnu-792.22.5/bsd/crypto/rc4/rc4.c) with [rc4.h](https://opensource.apple.com/source/xnu/xnu-792.2.4/bsd/crypto/rc4/rc4.h.auto.html)

**Comment by leelx78** [comment]
thanks a lot!
