### ISSUE TITLE
Is this library usable to cypher data on one device and decypher on another one ?

### ISSUE THREAD

**Issue by nicop4** [abderraouf-adjal/ArduinoSpritzCipher#14]
Hi 
I struggle using this library to transmit cyphered data between two devices.
Lets say I have one device creating, cyphering and transmitting data ; and another one receiving, decyphering and using data.

I setup the lib with key and nonce the same way on both devices.

```c
const byte key[8] = {0x13, 0xAB, 0xA2, 0x5C, 0xA3, 0x45, 0x98, 0x78};
const byte nonce[4] = {0xCA, 0x12, 0x45, 0x65};

spritz_ctx s_ctx;

spritz_setup_withIV(&s_ctx, key, sizeof(key), nonce, sizeof(nonce) );
``` 

I can decypher properly data on the RX side **ONLY** when both devices have booted roughly at the same time. If I restart only one of them, then the decyphered data is garbage.

Is there another initialization needed to set context ? Does the clock time is used to generate an internal seed ?

I did not see any "limitation" of this kind in documentation.

PS : I am aware that having this pre-shared key in both device and no actual random seed is not the way to really protect data, but my goal here is to *obfuscate* the data being transmitted over the air.

**Comment by abderraouf-adjal** [comment]
Hello, I think you are using the algorithm (a stream cipher) the wrong way.
A stream cipher has a "state" context (eg, `s_ctx`), which will make issues in the system if you keep it.

You need to do `spritz_setup_withIV()` for every new data batch going out (new cipher state for every new packet), and new nonce too.

One easy solution to use it without issues is sending the data as **independent packets** format, eg:

S = | new random nonce (16 byte) from RNG | 
E = | encrypted_data with known length |
PKT = S + E
or:
PKT = S + data_length + E

M = MAC(msg=PKT,key=preshared_key)

Transmit "M + PKT"; you can use the MAC (M) to check the authenticity of the message/packet from malicious changing or data corruption from noise...

- The nonce is ok to be public but make new random 16-bytes one for every packet.
- For the per-shared key, better use 16 or 32 bytes key (for 128-bit or 256bit entropy)

So yes, you have to "craft" the protocol (you can imagine it making you own TLS-PSK), and there are many ways to do it depending the security requirements and the computation+communication resources.

Another way is to use **2 states in each device**, one for D1->D2 and the other for D2->D1, but you must keep them synchronized with something like "data_counter" in-case some data lost during transmission so the RX can discard the lost length to keep them synchronized, this way you can save some data in the transmission by sending the nonce (S) once at the first communication hello world.

**Comment by nicop4** [comment]
Ok thanks for the clarifications. Indeed I did not understood that there was a cyphering stream under this.

I got it to work by calling `spritz_setup_withIV` with a new random nonce at each message, and passing this nonce not cyphered to the receiver ; and make the receiver use it in `spritz_setup_withIV` prior to decypher the payload as you suggested.

I did not include the MAC, will do maybe later.

The decypher part is like this, if this can help someone:
```c
memcpy(nonce, RcvBuffer, sizeof(nonce));
memcpy(input_buf, RcvBuffer + sizeof(nonce), sizeof(input_buf));

spritz_setup_withIV(&s_ctx, key, sizeof(key), nonce, sizeof(nonce) );
spritz_crypt(&s_ctx, input_buf, sizeof(input_buf), input_buf);
Serial.println("Data clear:");

for (size_t i = 0; i < sizeof(input_buf); i++)
{
  Serial.printf("%02X ", input_buf[i]);
}
```

Thanks for the help.
