### ISSUE TITLE
non standard implementation?

### ISSUE THREAD

**Issue by NateZimmer** [abderraouf-adjal/ArduinoSpritzCipher#4]
Perhaps more of a note than a bug. This library does not produce outputs that agree with common libs such as https://github.com/therealjampers/spritzjs/ . 
While both produce the same results as the test vectors in the paper here: https://people.csail.mit.edu/rivest/pubs/RS14.pdf , This lib uses XOR for encrypt as opposed to what is used in the paper/ other libs which is modular addition / modular subtraction. 
example solution: 

`void
spritz_crypt(spritz_ctx *ctx,
             const uint8_t *data, uint16_t dataLen,
             uint8_t *dataOut)
{
  uint16_t i;
  uint16_t temp = 0;
  for (i = 0; i < dataLen; i++) {
      temp = data[i] + drip(ctx);
      temp %=256;
    //dataOut[i] = data[i] ^ drip(ctx);
        dataOut[i] = temp;
  }
}`

**Comment by abderraouf-adjal** [comment]
Hello @NateZimmer ,
Thanks for checking the library.

I chose `XOR` because it's simple and fast, same operation for encryption and decryption (less code).

The use of `XOR` is mentioned inside the Spritz paper, exactly in `2.2 Encryption` page 5.

Quote from the paper:

> ... one could use exclusive-or rather than addition/subtraction. We call this variant Spritz-xor, but do not further discuss this variant in this paper.
