### ISSUE TITLE
Encrypt/decrypt success rate a function of key size

### ISSUE THREAD

**Issue by jmusther** [abderraouf-adjal/ArduinoSpritzCipher#6]
When performing encrypt followed by decrypt, the success rate (defined as the frequency at which the plaintext is regenerated) appears to be dependent on the key length.  I ran repetitive encrypt/decrypt cycles with different key lengths and found that:
A key length of 128 bytes results in about a 2% success rate
64 byte key results in about 75%
48 byte key results in about 80% 
32 byte key results in about 90%
16 byte key results in about 98%

Each of these tests ran for over 2000 cycles.  

Here's the code:
`#include <SpritzCipher.h>

long total = 0;
long success = 0;

const PROGMEM byte key[16] = {0xF4, 0x88, 0xE6, 0x3B, 0xA3, 0x1A, 0x79, 0x7F, 0x8D, 0x4C, 0x10, 0xEC, 0xB2, 0x1F, 0x84, 0x91};
                               
void spritzEnc(byte msg[], byte msgLen, const byte *key, byte keyLen){
  spritz_ctx s_ctx;

  spritz_setup(&s_ctx, key, keyLen);
  spritz_crypt(&s_ctx, msg, msgLen, msg);
}

void spritzDec(byte msg[], byte msgLen, const byte *key, byte keyLen){
  spritz_ctx s_ctx;

  spritz_setup(&s_ctx, key, keyLen);
  spritz_crypt(&s_ctx, msg, msgLen, msg);
}

void setup() {
  /* Initialize serial and wait for port to open */
  Serial.begin(9600);
  while (!Serial) {
    ; /* Wait for serial port to connect. Needed for Leonardo only */
  }

  /* initialize digital pin LED_BUILTIN (Most boards have this LED connected to digital pin 13) as an output */
  pinMode(LED_BUILTIN, OUTPUT);
  digitalWrite(LED_BUILTIN, LOW);
}

void loop() {
  byte testMsg[4] = { 'A', 'B', 'C', 'S'};
  
  spritzEnc(testMsg, sizeof(testMsg), key, sizeof(key));    // Encrypt

  spritzDec(testMsg, sizeof(testMsg), key, sizeof(key));    // Decrypt

  if (testMsg[0] == 'A' && testMsg[1] == 'B' && testMsg[2] == 'C' && testMsg[3] == 'S'){
    success = success + 1;
  }
  total = total + 1;
  float sp = (float(success) / float(total))*100.0;

  Serial.print("Cycles = ");
  Serial.print(total);
  Serial.print(" success = ");
  Serial.print(success);
  Serial.print(" or ");
  Serial.print(sp, 2);
  Serial.println(" %");

}
`

**Comment by abderraouf-adjal** [comment]
Hi Mr. @jmusther,
Thanks for opening the issues.

I like you to consider that ArduinoSpritzCipher is well carefully written.

The issue is a memory corruption and NOT in the lib code/memory-zone; The issue is because of this code line:

`const PROGMEM byte key[16] .....`

The `PROGMEM` is the problem, you should NOT deal with it like a normal data in RAM, take a look: [AVR Libc Reference Manual Data in Program Space](https://www.microchip.com/webdoc/AVRLibcReferenceManual/pgmspace_1pgmspace_data.html) .

I consider to add a warning in the documentation about using `PROGMEM`, tell me your opinion.

**Comment by abderraouf-adjal** [comment]
Doing this will probably solve your problem:
`memcpy_P(buf, (PGM_P)pgm_read_word(&key), sizeof(buf));`
`spritzEnc(testMsg, sizeof(testMsg), buf, sizeof(buf));`

**Comment by jmusther** [comment]
Hello, and thank you very much for your response.  I should have realised that this was the problem, but I didn't, so personally I think a warning in the documentation would be helpful.  

Thank you once again for a very useful resource!
